// Manual additions to EditorTerrainBuildSplatMapKeys for TextureMask and Heatmap support.
// These would normally be generated by Stride's shader code generator.

#nullable enable

using Stride.Graphics;
using Stride.Rendering;

namespace Terrain.Editor;

public static partial class EditorTerrainBuildSplatMapKeys
{
    public static readonly ObjectParameterKey<Texture> TextureMaskResource = ParameterKeys.NewObject<Texture>();
    public static readonly ObjectParameterKey<SamplerState> TextureMaskSampler = ParameterKeys.NewObject<SamplerState>();
    public static readonly ValueParameterKey<int> HeatmapLayerIndex = ParameterKeys.NewValue<int>();
    public static readonly ValueParameterKey<int> HeatmapEnabled = ParameterKeys.NewValue<int>();
}
