// Manual additions to EditorTerrainDiffuseKeys for debug view support.
// These would normally be generated by Stride's shader code generator.

#nullable enable

using Stride.Graphics;
using Stride.Rendering;

namespace Terrain.Editor;

public static partial class EditorTerrainDiffuseKeys
{
    public static readonly ObjectParameterKey<Texture> BiomeMaskDebugTexture = ParameterKeys.NewObject<Texture>();
    public static readonly ObjectParameterKey<SamplerState> BiomeMaskDebugSampler = ParameterKeys.NewObject<SamplerState>();
    public static readonly ObjectParameterKey<Texture> HeatmapTexture = ParameterKeys.NewObject<Texture>();
    public static readonly ObjectParameterKey<SamplerState> HeatmapSampler = ParameterKeys.NewObject<SamplerState>();
    public static readonly ValueParameterKey<int> DebugViewMode = ParameterKeys.NewValue<int>();
    public static readonly ValueParameterKey<int> HeatmapLayerIndex = ParameterKeys.NewValue<int>();
}
