// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Terrain.Editor
{
    public static partial class EditorTerrainHeightParametersKeys
    {
        public static readonly ObjectParameterKey<Texture> HeightmapSlice0 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HeightmapSlice1 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HeightmapSlice2 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HeightmapSlice3 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HeightmapSlice4 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HeightmapSlice5 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HeightmapSlice6 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HeightmapSlice7 = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<float> HeightScale = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<int> BaseChunkSize = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<int> SliceCount = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<int> HeightmapSlicePadding = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<Int4> HeightmapSliceBounds0 = ParameterKeys.NewValue<Int4>();
        public static readonly ValueParameterKey<Int4> HeightmapSliceBounds1 = ParameterKeys.NewValue<Int4>();
        public static readonly ValueParameterKey<Int4> HeightmapSliceBounds2 = ParameterKeys.NewValue<Int4>();
        public static readonly ValueParameterKey<Int4> HeightmapSliceBounds3 = ParameterKeys.NewValue<Int4>();
        public static readonly ValueParameterKey<Int4> HeightmapSliceBounds4 = ParameterKeys.NewValue<Int4>();
        public static readonly ValueParameterKey<Int4> HeightmapSliceBounds5 = ParameterKeys.NewValue<Int4>();
        public static readonly ValueParameterKey<Int4> HeightmapSliceBounds6 = ParameterKeys.NewValue<Int4>();
        public static readonly ValueParameterKey<Int4> HeightmapSliceBounds7 = ParameterKeys.NewValue<Int4>();
    }
}
