// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Terrain.Editor
{
    public static partial class EditorTerrainDiffuseKeys
    {
        public static readonly ObjectParameterKey<Texture> DefaultDiffuseTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> TerrainDiffuseRepeatSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ValueParameterKey<float> DiffuseWorldRepeatSize = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Color4> BaseColor = ParameterKeys.NewValue<Color4>();
        public static readonly ValueParameterKey<Vector2> HeightmapDimensionsInSamples = ParameterKeys.NewValue<Vector2>();

        // 材质索引图参数
        public static readonly ObjectParameterKey<Texture> MaterialIndexMap = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> MaterialIndexSampler = ParameterKeys.NewObject<SamplerState>();

        // 材质纹理数组参数
        public static readonly ObjectParameterKey<Texture> MaterialAlbedoArray = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> MaterialAlbedoSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ValueParameterKey<int> MaterialArraySize = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<float> MaterialTilingScale = ParameterKeys.NewValue<float>();
    }
}
