// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Terrain.Editor
{
    public static partial class EditorTerrainBuildSplatMapKeys
    {
        public static readonly ObjectParameterKey<Texture> BiomeMaskTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Buffer> Biomes = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> Layers = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> Modifiers = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Texture> OutputIndexMap = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> OutputWeightMap = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<int> CurrentSliceIndex = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<int> OutputWidth = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<int> OutputHeight = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<int> BiomeMaskWidth = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<int> BiomeMaskHeight = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<int> BiomeCount = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<int> LayerCount = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<int> ModifierCount = ParameterKeys.NewValue<int>();
    }
}
