// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Terrain.Editor
{
    public static partial class PathRiverSurfaceKeys
    {
        public static readonly ValueParameterKey<Color4> ShallowColor = ParameterKeys.NewValue<Color4>();
        public static readonly ValueParameterKey<Color4> DeepColor = ParameterKeys.NewValue<Color4>();
        public static readonly ValueParameterKey<float> EdgeFadeStart = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> FlowTiling = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> FlowStrength = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> HighlightStrength = ParameterKeys.NewValue<float>();
    }
}
