// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Terrain.Editor
{
    public static partial class PathRoadSurfaceKeys
    {
        public static readonly ObjectParameterKey<Texture> DiffuseTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> DiffuseSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<Texture> NormalTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> NormalSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<Texture> PropertiesTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> PropertiesSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ValueParameterKey<Color4> BaseColor = ParameterKeys.NewValue<Color4>();
        public static readonly ValueParameterKey<float> EdgeFadeStart = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> NormalStrength = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> EndFadeoutFactor = ParameterKeys.NewValue<float>();
    }
}
