// Failed to parse the shader:
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(5,9): error  : Syntax error, expected: } typedef identifier bool int uint float unorm snorm half double vector bool1 bool2 bool3 bool4 int1 int2 int3 int4 uint1 uint2 uint3 uint4 float1 float2 float3 float4 half1 half2 half3 half4 double1 double2 double3 double4 matrix bool1x1 bool1x2 bool1x3 bool1x4 bool2x1 bool2x2 bool2x3 bool2x4 bool3x1 bool3x2 bool3x3 bool3x4 bool4x1 bool4x2 bool4x3 bool4x4 int1x1 int1x2 int1x3 int1x4 int2x1 int2x2 int2x3 int2x4 int3x1 int3x2 int3x3 int3x4 int4x1 int4x2 int4x3 int4x4 uint1x1 uint1x2 uint1x3 uint1x4 uint2x1 uint2x2 uint2x3 uint2x4 uint3x1 uint3x2 uint3x3 uint3x4 uint4x1 uint4x2 uint4x3 uint4x4 float1x1 float1x2 float1x3 float1x4 float2x1 float2x2 float2x3 float2x4 float3x1 float3x2 float3x3 float3x4 float4x1 float4x2 float4x3 float4x4 half1x1 half1x2 half1x3 half1x4 half2x1 half2x2 half2x3 half2x4 half3x1 half3x2 half3x3 half3x4 half4x1 half4x2 half4x3 half4x4 double1x1 double1x2 double1x3 double1x4 double2x1 double2x2 double2x3 double2x4 double3x1 double3x2 double3x3 double3x4 double4x1 double4x2 double4x3 double4x4 string struct sampler sampler1D sampler2D sampler3D samplerCUBE Buffer BlendState DepthStencilState RasterizerState SamplerState sampler_state SamplerComparisonState texture Texture1D texture1D Texture1DArray texture1DArray Texture2D texture2D Texture2DArray texture2DArray Texture3D texture3D TextureCube textureCube RWBuffer RWTexture1D RWTexture1DArray RWTexture2D RWTexture2DArray RWTexture3D Texture2DMS Texture2DMSArray ByteAddressBuffer RWByteAddressBuffer AppendStructuredBuffer ConsumeStructuredBuffer RWStructuredBuffer StructuredBuffer InputPatch OutputPatch interface class LineStream PointStream TriangleStream StreamOutputObject var Constants Input Input2 Output Streams shader void Semantic LinkType MemberName const uniform extern nointerpolation precise shared groupshared static volatile row_major column_major linear centroid noperspective sample unsigned inline override abstract stream patchstream stage clone compose internal cbuffer tbuffer rgroup discard { ; point integer_literal float_literal true false ( compile asm ++ -- + - ! ~ * if switch while do for foreach continue break return mixin using [
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(6,9): error  : Syntax error, expected: < identifier sample point stage ; [ ( . ++ -- = += -= *= /= %= &= |= ^= <<= >>= * / % + - << >> > <= >= == != & ^ | && || ? ,
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(7,39): error  : Syntax error, expected: identifier
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(7,46): error  : Syntax error, expected: identifier
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(10,13): error  : Failed to create AST node for non-terminal [variable_declaration_raw], error: Object reference not set to an instance of an object.
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(10,24): error  : Syntax error, expected: { identifier sample point stage ;
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(11,13): error  : Failed to create AST node for non-terminal [variable_declaration_raw], error: Object reference not set to an instance of an object.
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(11,31): error  : Syntax error, expected: { identifier sample point stage ;
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(12,13): error  : Failed to create AST node for non-terminal [variable_declaration_raw], error: Object reference not set to an instance of an object.
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(12,29): error  : Syntax error, expected: { identifier sample point stage ;
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(15,9): error  : Syntax error, expected: } typedef ; namespace using [ identifier bool int uint float unorm snorm half double vector bool1 bool2 bool3 bool4 int1 int2 int3 int4 uint1 uint2 uint3 uint4 float1 float2 float3 float4 half1 half2 half3 half4 double1 double2 double3 double4 matrix bool1x1 bool1x2 bool1x3 bool1x4 bool2x1 bool2x2 bool2x3 bool2x4 bool3x1 bool3x2 bool3x3 bool3x4 bool4x1 bool4x2 bool4x3 bool4x4 int1x1 int1x2 int1x3 int1x4 int2x1 int2x2 int2x3 int2x4 int3x1 int3x2 int3x3 int3x4 int4x1 int4x2 int4x3 int4x4 uint1x1 uint1x2 uint1x3 uint1x4 uint2x1 uint2x2 uint2x3 uint2x4 uint3x1 uint3x2 uint3x3 uint3x4 uint4x1 uint4x2 uint4x3 uint4x4 float1x1 float1x2 float1x3 float1x4 float2x1 float2x2 float2x3 float2x4 float3x1 float3x2 float3x3 float3x4 float4x1 float4x2 float4x3 float4x4 half1x1 half1x2 half1x3 half1x4 half2x1 half2x2 half2x3 half2x4 half3x1 half3x2 half3x3 half3x4 half4x1 half4x2 half4x3 half4x4 double1x1 double1x2 double1x3 double1x4 double2x1 double2x2 double2x3 double2x4 double3x1 double3x2 double3x3 double3x4 double4x1 double4x2 double4x3 double4x4 string struct sampler sampler1D sampler2D sampler3D samplerCUBE Buffer BlendState DepthStencilState RasterizerState SamplerState sampler_state SamplerComparisonState texture Texture1D texture1D Texture1DArray texture1DArray Texture2D texture2D Texture2DArray texture2DArray Texture3D texture3D TextureCube textureCube RWBuffer RWTexture1D RWTexture1DArray RWTexture2D RWTexture2DArray RWTexture3D Texture2DMS Texture2DMSArray ByteAddressBuffer RWByteAddressBuffer AppendStructuredBuffer ConsumeStructuredBuffer RWStructuredBuffer StructuredBuffer InputPatch OutputPatch interface class LineStream PointStream TriangleStream StreamOutputObject var Constants Input Input2 Output Streams shader void Semantic LinkType MemberName const uniform extern nointerpolation precise shared groupshared static volatile row_major column_major linear centroid noperspective sample unsigned inline override abstract stream patchstream stage clone compose internal cbuffer tbuffer rgroup technique Technique technique10 Technique10 technique11 Technique11 params partial enum effect
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(16,9): error  : Syntax error, expected: identifier sample point stage operator ;
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(16,10): error  : Expecting identifier for variable declaration [RiverSurfacePass]
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(17,26): error  : Syntax error, expected: identifier sample point stage operator ;
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(17,27): error  : Expecting identifier for variable declaration [VertexShader]
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(17,38): error  : Syntax error, expected: identifier sample point stage operator ;
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(17,39): error  : Expecting identifier for variable declaration [ShaderBase]
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(17,46): error  : Syntax error, expected: identifier sample point stage operator ;
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(17,47): error  : Expecting identifier for variable declaration [Streams]
E:/Stride Projects/Terrain/Terrain.Editor/Effects/RiverEffect.sdfx(17,61): error  : Syntax error, expected: identifier sample point stage operator ;
