// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Terrain.Editor
{
    public static partial class RiverSurfaceKeys
    {
        public static readonly ValueParameterKey<float> _FlowNormalSpeed = ParameterKeys.NewValue<float>(0.075f);
        public static readonly ValueParameterKey<float> _FlowNormalUvScale = ParameterKeys.NewValue<float>(0.4f);
        public static readonly ValueParameterKey<float> _RiverFoamFactor = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<float> _NoiseScale = ParameterKeys.NewValue<float>(0.25f);
        public static readonly ValueParameterKey<float> _NoiseSpeed = ParameterKeys.NewValue<float>(2.0f);
        public static readonly ValueParameterKey<float> _FlattenMult = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _BankFade = ParameterKeys.NewValue<float>(0.025f);
        public static readonly ValueParameterKey<float> _Depth = ParameterKeys.NewValue<float>(0.15f);
        public static readonly ValueParameterKey<float> _DepthWidthPower = ParameterKeys.NewValue<float>(2.0f);
        public static readonly ValueParameterKey<float> _MapExtent = ParameterKeys.NewValue<float>(4096.0f);
        public static readonly ValueParameterKey<Vector2> _MapWorldSize = ParameterKeys.NewValue<Vector2>(new Vector2(4096.0f,4096.0f));
        public static readonly ValueParameterKey<float> _WorldToMapUnitScale = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<Vector3> _CameraWorldPosition = ParameterKeys.NewValue<Vector3>(new Vector3(0.0f,0.0f,0.0f));
        public static readonly ValueParameterKey<Vector2> _ViewSize = ParameterKeys.NewValue<Vector2>(new Vector2(1.0f,1.0f));
        public static readonly ValueParameterKey<Matrix> _ViewMatrix = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<float> _GlobalTime = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> _FlatMapLerp = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> _WaterZoomedInZoomedOutFactor = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> _WaterDiffuseMultiplier = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<Vector3> _WaterColorMapTint = ParameterKeys.NewValue<Vector3>(new Vector3(0.0f,0.0f,0.0f));
        public static readonly ValueParameterKey<float> _WaterColorMapTintFactor = ParameterKeys.NewValue<float>(0.010695934f);
        public static readonly ValueParameterKey<float> _WaterRefractionScale = ParameterKeys.NewValue<float>(500.0f);
        public static readonly ValueParameterKey<float> _WaterRefractionShoreMaskDepth = ParameterKeys.NewValue<float>(3.0f);
        public static readonly ValueParameterKey<float> _WaterRefractionShoreMaskSharpness = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _WaterRefractionFade = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _WaterFadeShoreMaskDepth = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<float> _WaterFadeShoreMaskSharpness = ParameterKeys.NewValue<float>(5.0f);
        public static readonly ValueParameterKey<float> _WaterSeeThroughDensity = ParameterKeys.NewValue<float>(0.8f);
        public static readonly ValueParameterKey<float> _WaterSeeThroughShoreMaskDepth = ParameterKeys.NewValue<float>(20.0f);
        public static readonly ValueParameterKey<float> _WaterSeeThroughShoreMaskSharpness = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _WaterFresnelBias = ParameterKeys.NewValue<float>(0.01f);
        public static readonly ValueParameterKey<float> _WaterFresnelPow = ParameterKeys.NewValue<float>(4.3f);
        public static readonly ValueParameterKey<float> _WaterReflectionNormalFlatten = ParameterKeys.NewValue<float>(3.0f);
        public static readonly ValueParameterKey<float> _WaterSpecular = ParameterKeys.NewValue<float>(0.05f);
        public static readonly ValueParameterKey<float> _WaterSpecularFactor = ParameterKeys.NewValue<float>(0.01f);
        public static readonly ValueParameterKey<float> _WaterGlossBase = ParameterKeys.NewValue<float>(0.7f);
        public static readonly ValueParameterKey<float> _WaterGlossScale = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _WaterCubemapIntensity = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<Vector2> _WaterWave1Scale = ParameterKeys.NewValue<Vector2>(new Vector2(10.0f,10.0f));
        public static readonly ValueParameterKey<float> _WaterWave1Rotation = ParameterKeys.NewValue<float>(-0.35f);
        public static readonly ValueParameterKey<float> _WaterWave1Speed = ParameterKeys.NewValue<float>(0.01f);
        public static readonly ValueParameterKey<Vector2> _WaterWave2Scale = ParameterKeys.NewValue<Vector2>(new Vector2(2.0f,1.0f));
        public static readonly ValueParameterKey<float> _WaterWave2Rotation = ParameterKeys.NewValue<float>(-1.6f);
        public static readonly ValueParameterKey<float> _WaterWave2Speed = ParameterKeys.NewValue<float>(0.016f);
        public static readonly ValueParameterKey<Vector2> _WaterWave3Scale = ParameterKeys.NewValue<Vector2>(new Vector2(0.2f,0.1f));
        public static readonly ValueParameterKey<float> _WaterWave3Rotation = ParameterKeys.NewValue<float>(1.725075f);
        public static readonly ValueParameterKey<float> _WaterWave3Speed = ParameterKeys.NewValue<float>(0.005f);
        public static readonly ValueParameterKey<float> _WaterWave1NormalFlatten = ParameterKeys.NewValue<float>(1.5f);
        public static readonly ValueParameterKey<float> _WaterWave2NormalFlatten = ParameterKeys.NewValue<float>(1.5f);
        public static readonly ValueParameterKey<float> _WaterWave3NormalFlatten = ParameterKeys.NewValue<float>(1.5f);
        public static readonly ValueParameterKey<float> _WaterFlowNormalFlatten = ParameterKeys.NewValue<float>(1.5f);
        public static readonly ValueParameterKey<float> _WaterHeight = ParameterKeys.NewValue<float>(3.0f);
        public static readonly ValueParameterKey<Vector3> _DefaultEnvironmentSunDiffuse = ParameterKeys.NewValue<Vector3>(new Vector3(1.0f,0.86783814f,0.7548521f));
        public static readonly ValueParameterKey<float> _DefaultEnvironmentSunIntensity = ParameterKeys.NewValue<float>(20.0f);
        public static readonly ValueParameterKey<Vector3> _WaterToSunDir = ParameterKeys.NewValue<Vector3>(new Vector3(-0.543915f,0.5933618f,0.5933618f));
        public static readonly ValueParameterKey<Vector3> _TerrainSunnySunDir = ParameterKeys.NewValue<Vector3>(new Vector3(-0.4755282f,0.58778524f,0.65450853f));
        public static readonly ValueParameterKey<Vector3> _ToWaterSunnySunDir = ParameterKeys.NewValue<Vector3>(new Vector3(-0.4755282f,0.58778524f,0.65450853f));
        public static readonly ValueParameterKey<Vector3> _ToWaterOvercastSunDir = ParameterKeys.NewValue<Vector3>(new Vector3(-0.4755282f,0.58778524f,0.65450853f));
        public static readonly ValueParameterKey<Vector2> _MapSadowTintNoiseUVTiling = ParameterKeys.NewValue<Vector2>(new Vector2(500.0f,500.0f));
        public static readonly ValueParameterKey<float> _MapSadowTintStrength = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<float> _MapSadowTintThresholdMin = ParameterKeys.NewValue<float>(0.1f);
        public static readonly ValueParameterKey<float> _MapSadowTintThresholdMax = ParameterKeys.NewValue<float>(0.4f);
        public static readonly ValueParameterKey<Vector2> _InverseWorldSize = ParameterKeys.NewValue<Vector2>(new Vector2(0.000244140625f,0.000244140625f));
        public static readonly ValueParameterKey<float> _HasCloudShadowEnabled = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _FogMax = ParameterKeys.NewValue<float>(0.2f);
        public static readonly ValueParameterKey<float> _FogBegin2 = ParameterKeys.NewValue<float>(5728.3252f);
        public static readonly ValueParameterKey<float> _FogEnd2 = ParameterKeys.NewValue<float>(208999.7031f);
        public static readonly ValueParameterKey<Vector3> _FogColor = ParameterKeys.NewValue<Vector3>(new Vector3(0.07805659f,0.1869885f,0.3344578f));
        public static readonly ValueParameterKey<Vector3> _RelativeFogColor = ParameterKeys.NewValue<Vector3>(new Vector3(0.6f,0.2f,-0.2f));
        public static readonly ValueParameterKey<float> _RelativeFogBegin = ParameterKeys.NewValue<float>(100.0f);
        public static readonly ValueParameterKey<float> _RelativeFogEnd = ParameterKeys.NewValue<float>(400.0f);
        public static readonly ValueParameterKey<float> _RelativeFogHeightBegin = ParameterKeys.NewValue<float>(10.0f);
        public static readonly ValueParameterKey<float> _RelativeFogHeightEnd = ParameterKeys.NewValue<float>(40.0f);
        public static readonly ValueParameterKey<float> _WaterFoamScale = ParameterKeys.NewValue<float>(0.3f);
        public static readonly ValueParameterKey<float> _WaterFoamDistortFactor = ParameterKeys.NewValue<float>(0.1f);
        public static readonly ValueParameterKey<float> _WaterFoamShoreMaskDepth = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> _WaterFoamShoreMaskSharpness = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _WaterFoamNoiseScale = ParameterKeys.NewValue<float>(0.005f);
        public static readonly ValueParameterKey<float> _WaterFoamNoiseSpeed = ParameterKeys.NewValue<float>(0.025f);
        public static readonly ValueParameterKey<float> _WaterFoamStrength = ParameterKeys.NewValue<float>(0.6f);
        public static readonly ValueParameterKey<Vector4> WaterColorShallow = ParameterKeys.NewValue<Vector4>(new Vector4(0.0055146287f,0.0078107193f,0.0120865023f,1.0f));
        public static readonly ValueParameterKey<Vector4> WaterColorDeep = ParameterKeys.NewValue<Vector4>(new Vector4(0.0001385075f,0.0001974951f,0.0002262951f,1.0f));
        public static readonly ObjectParameterKey<Texture> RefractionTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> RefractionSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<Texture> AmbientNormalTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FlowNormalTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FoamTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FoamRampTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FoamMapTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FoamNoiseTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> WaterColorTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> ShadowNoiseTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HeightmapSlice0 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HeightmapSlice1 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HeightmapSlice2 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HeightmapSlice3 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HeightmapSlice4 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HeightmapSlice5 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HeightmapSlice6 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> HeightmapSlice7 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> ReflectionSpecularTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> ReflectionSpecularSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<SamplerState> WaterColorSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<SamplerState> WaterTextureSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<SamplerState> ShadowNoiseSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<SamplerState> TerrainHeightSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ValueParameterKey<int> SliceCount = ParameterKeys.NewValue<int>(0);
        public static readonly ValueParameterKey<float> HeightScale = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<Vector2> _TerrainWorldOffsetXZ = ParameterKeys.NewValue<Vector2>(new Vector2(0.0f,0.0f));
        public static readonly ValueParameterKey<Vector2> _TerrainNormalStepSize = ParameterKeys.NewValue<Vector2>(new Vector2(1.0f,1.0f));
        public static readonly ValueParameterKey<Vector2> _WorldSpaceToTerrain0To1 = ParameterKeys.NewValue<Vector2>(new Vector2(1.0f,1.0f));
        public static readonly ValueParameterKey<Vector4> HeightmapSliceBounds0 = ParameterKeys.NewValue<Vector4>(new Vector4(0.0f,0.0f,1.0f,1.0f));
        public static readonly ValueParameterKey<Vector4> HeightmapSliceBounds1 = ParameterKeys.NewValue<Vector4>(new Vector4(0.0f,0.0f,1.0f,1.0f));
        public static readonly ValueParameterKey<Vector4> HeightmapSliceBounds2 = ParameterKeys.NewValue<Vector4>(new Vector4(0.0f,0.0f,1.0f,1.0f));
        public static readonly ValueParameterKey<Vector4> HeightmapSliceBounds3 = ParameterKeys.NewValue<Vector4>(new Vector4(0.0f,0.0f,1.0f,1.0f));
        public static readonly ValueParameterKey<Vector4> HeightmapSliceBounds4 = ParameterKeys.NewValue<Vector4>(new Vector4(0.0f,0.0f,1.0f,1.0f));
        public static readonly ValueParameterKey<Vector4> HeightmapSliceBounds5 = ParameterKeys.NewValue<Vector4>(new Vector4(0.0f,0.0f,1.0f,1.0f));
        public static readonly ValueParameterKey<Vector4> HeightmapSliceBounds6 = ParameterKeys.NewValue<Vector4>(new Vector4(0.0f,0.0f,1.0f,1.0f));
        public static readonly ValueParameterKey<Vector4> HeightmapSliceBounds7 = ParameterKeys.NewValue<Vector4>(new Vector4(0.0f,0.0f,1.0f,1.0f));
    }
}
