// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Terrain.Editor
{
    public static partial class RiverSurfaceKeys
    {
        public static readonly ValueParameterKey<float> _FlowNormalSpeed = ParameterKeys.NewValue<float>(0.075f);
        public static readonly ValueParameterKey<float> _FlowNormalUvScale = ParameterKeys.NewValue<float>(0.4f);
        public static readonly ValueParameterKey<float> _RiverFoamFactor = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<float> _NoiseScale = ParameterKeys.NewValue<float>(0.25f);
        public static readonly ValueParameterKey<float> _NoiseSpeed = ParameterKeys.NewValue<float>(2.0f);
        public static readonly ValueParameterKey<float> _BankFade = ParameterKeys.NewValue<float>(0.02f);
        public static readonly ValueParameterKey<float> _Depth = ParameterKeys.NewValue<float>(0.15f);
        public static readonly ValueParameterKey<float> _DepthWidthPower = ParameterKeys.NewValue<float>(2.0f);
        public static readonly ValueParameterKey<float> _GlobalTime = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> _FlatMapLerp = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> _ZoomBlendOut = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _ShadowTermFallback = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _CloudMaskFallback = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<Vector4> WaterColorShallow = ParameterKeys.NewValue<Vector4>(new Vector4(0.0f,0.3f,0.5f,0.7f));
        public static readonly ValueParameterKey<Vector4> WaterColorDeep = ParameterKeys.NewValue<Vector4>(new Vector4(0.0f,0.05f,0.15f,0.85f));
        public static readonly ObjectParameterKey<Texture> RefractionTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> RefractionSampler = ParameterKeys.NewObject<SamplerState>();
    }
}
