// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Terrain
{
    public static partial class OceanSurfaceKeys
    {
        public static readonly ValueParameterKey<Vector4> ShallowColor = ParameterKeys.NewValue<Vector4>(new Vector4(0.08f,0.32f,0.42f,1.0f));
        public static readonly ValueParameterKey<Vector4> DeepColor = ParameterKeys.NewValue<Vector4>(new Vector4(0.01f,0.08f,0.16f,1.0f));
        public static readonly ValueParameterKey<float> _OceanRoughness = ParameterKeys.NewValue<float>(0.08f);
        public static readonly ValueParameterKey<float> _WaveScale = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _WaterHeight = ParameterKeys.NewValue<float>(3.0f);
        public static readonly ValueParameterKey<Vector2> _MapWorldSize = ParameterKeys.NewValue<Vector2>(new Vector2(4096.0f,4096.0f));
        public static readonly ValueParameterKey<Vector3> _CameraWorldPosition = ParameterKeys.NewValue<Vector3>(new Vector3(0.0f,0.0f,0.0f));
        public static readonly ValueParameterKey<Vector2> _ViewSize = ParameterKeys.NewValue<Vector2>(new Vector2(1.0f,1.0f));
        public static readonly ValueParameterKey<Vector2> _RefractionTextureSize = ParameterKeys.NewValue<Vector2>(new Vector2(1.0f,1.0f));
        public static readonly ValueParameterKey<Matrix> _ViewMatrix = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<float> _GlobalTime = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> _WaterFlowTime = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> _WaterSeeThroughDensity = ParameterKeys.NewValue<float>(0.8f);
        public static readonly ValueParameterKey<float> _WaterRefractionScale = ParameterKeys.NewValue<float>(500.0f);
        public static readonly ValueParameterKey<float> _WaterRefractionShoreMaskDepth = ParameterKeys.NewValue<float>(3.0f);
        public static readonly ValueParameterKey<float> _WaterRefractionShoreMaskSharpness = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _WaterFadeShoreMaskDepth = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<float> _WaterFadeShoreMaskSharpness = ParameterKeys.NewValue<float>(5.0f);
        public static readonly ValueParameterKey<float> _WaterFoamShoreMaskDepth = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> _WaterFoamShoreMaskSharpness = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<Vector2> _WaterWave1Scale = ParameterKeys.NewValue<Vector2>(new Vector2(10.0f,10.0f));
        public static readonly ValueParameterKey<float> _WaterWave1Rotation = ParameterKeys.NewValue<float>(-0.35f);
        public static readonly ValueParameterKey<float> _WaterWave1Speed = ParameterKeys.NewValue<float>(0.01f);
        public static readonly ValueParameterKey<float> _WaterWave1NormalFlatten = ParameterKeys.NewValue<float>(1.5f);
        public static readonly ValueParameterKey<Vector2> _WaterWave2Scale = ParameterKeys.NewValue<Vector2>(new Vector2(2.0f,1.0f));
        public static readonly ValueParameterKey<float> _WaterWave2Rotation = ParameterKeys.NewValue<float>(-1.6f);
        public static readonly ValueParameterKey<float> _WaterWave2Speed = ParameterKeys.NewValue<float>(0.016f);
        public static readonly ValueParameterKey<float> _WaterWave2NormalFlatten = ParameterKeys.NewValue<float>(1.5f);
        public static readonly ValueParameterKey<Vector2> _WaterWave3Scale = ParameterKeys.NewValue<Vector2>(new Vector2(0.2f,0.1f));
        public static readonly ValueParameterKey<float> _WaterWave3Rotation = ParameterKeys.NewValue<float>(1.725075f);
        public static readonly ValueParameterKey<float> _WaterWave3Speed = ParameterKeys.NewValue<float>(0.005f);
        public static readonly ValueParameterKey<float> _WaterWave3NormalFlatten = ParameterKeys.NewValue<float>(1.5f);
        public static readonly ValueParameterKey<float> _WaterAmbientNormalFlatten = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _WaterFlowNormalScale = ParameterKeys.NewValue<float>(8.0f);
        public static readonly ValueParameterKey<float> _WaterFlowNormalFlatten = ParameterKeys.NewValue<float>(1.5f);
        public static readonly ValueParameterKey<Vector2> _WaterFlowMapSize = ParameterKeys.NewValue<Vector2>(new Vector2(256.0f,256.0f));
        public static readonly ValueParameterKey<float> _WaterFlowNormalSpeed = ParameterKeys.NewValue<float>(0.05f);
        public static readonly ValueParameterKey<float> _WaterFoamScale = ParameterKeys.NewValue<float>(0.3f);
        public static readonly ValueParameterKey<float> _WaterFoamDistortFactor = ParameterKeys.NewValue<float>(0.1f);
        public static readonly ValueParameterKey<float> _WaterFoamNoiseScale = ParameterKeys.NewValue<float>(0.005f);
        public static readonly ValueParameterKey<float> _WaterFoamNoiseSpeed = ParameterKeys.NewValue<float>(0.025f);
        public static readonly ValueParameterKey<float> _WaterFoamStrength = ParameterKeys.NewValue<float>(0.6f);
        public static readonly ValueParameterKey<float> _WaterFresnelBias = ParameterKeys.NewValue<float>(0.01f);
        public static readonly ValueParameterKey<float> _WaterFresnelPow = ParameterKeys.NewValue<float>(4.3f);
        public static readonly ValueParameterKey<float> _WaterReflectionNormalFlatten = ParameterKeys.NewValue<float>(3.0f);
        public static readonly ValueParameterKey<float> _WaterReflectionIntensity = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _WaterSpecular = ParameterKeys.NewValue<float>(0.05f);
        public static readonly ValueParameterKey<float> _WaterGlossBase = ParameterKeys.NewValue<float>(0.7f);
        public static readonly ValueParameterKey<float> _WaterGlossScale = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ObjectParameterKey<Texture> WaterColorTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> AmbientNormalTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FlowMapTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FlowNormalTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FoamTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FoamRampTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FoamMapTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FoamNoiseTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> RefractionTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> OceanTextureSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<SamplerState> RefractionSampler = ParameterKeys.NewObject<SamplerState>();
    }
}
