// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Terrain
{
    public static partial class OceanSurfaceKeys
    {
        public static readonly ValueParameterKey<Vector4> ShallowColor = ParameterKeys.NewValue<Vector4>(new Vector4(0.08f,0.32f,0.42f,1.0f));
        public static readonly ValueParameterKey<Vector4> DeepColor = ParameterKeys.NewValue<Vector4>(new Vector4(0.01f,0.08f,0.16f,1.0f));
        public static readonly ValueParameterKey<float> _OceanRoughness = ParameterKeys.NewValue<float>(0.08f);
        public static readonly ValueParameterKey<float> _WaveScale = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _WaterHeight = ParameterKeys.NewValue<float>(3.0f);
        public static readonly ValueParameterKey<Vector2> _MapWorldSize = ParameterKeys.NewValue<Vector2>(new Vector2(4096.0f,4096.0f));
        public static readonly ValueParameterKey<Vector3> _CameraWorldPosition = ParameterKeys.NewValue<Vector3>(new Vector3(0.0f,0.0f,0.0f));
        public static readonly ValueParameterKey<float> _GlobalTime = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ObjectParameterKey<Texture> WaterColorTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> AmbientNormalTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FlowMapTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FlowNormalTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FoamTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FoamRampTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FoamMapTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> FoamNoiseTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> OceanTextureSampler = ParameterKeys.NewObject<SamplerState>();
    }
}
