// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Terrain
{
    public static partial class MaterialTerrainDiffuseKeys
    {
        public static readonly ObjectParameterKey<Texture> IndexMapArray = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> MaterialIndexSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<Texture> MaterialAlbedoArray = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> MaterialAlbedoSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<Texture> MaterialNormalArray = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> MaterialNormalSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ValueParameterKey<float> MaterialTilingScale = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> DetailContrast = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<int> MaterialArraySize = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<int> MaterialNormalArraySize = ParameterKeys.NewValue<int>();
    }
}
