//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerrainPreProcessor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerrainPreProcessor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain PreProcessor.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error.
        /// </summary>
        public static string ConfigurationError {
            get {
                return ResourceManager.GetString("ConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height Map:.
        /// </summary>
        public static string HeightMap {
            get {
                return ResourceManager.GetString("HeightMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select height map file (*.png, *.raw, *.r16).
        /// </summary>
        public static string HeightMapWatermark {
            get {
                return ResourceManager.GetString("HeightMapWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Files.
        /// </summary>
        public static string InputFiles {
            get {
                return ResourceManager.GetString("InputFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaf Node Size.
        /// </summary>
        public static string LeafNodeSize {
            get {
                return ResourceManager.GetString("LeafNodeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File.
        /// </summary>
        public static string OutputFile {
            get {
                return ResourceManager.GetString("OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Path:.
        /// </summary>
        public static string OutputPath {
            get {
                return ResourceManager.GetString("OutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto use height map directory.
        /// </summary>
        public static string OutputPathWatermark {
            get {
                return ResourceManager.GetString("OutputPathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Complete!.
        /// </summary>
        public static string ProcessingComplete {
            get {
                return ResourceManager.GetString("ProcessingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Error.
        /// </summary>
        public static string ProcessingError {
            get {
                return ResourceManager.GetString("ProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Parameters.
        /// </summary>
        public static string ProcessingParameters {
            get {
                return ResourceManager.GetString("ProcessingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Progress.
        /// </summary>
        public static string ProcessingProgress {
            get {
                return ResourceManager.GetString("ProcessingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Terrain Data.
        /// </summary>
        public static string ProcessingTerrainData {
            get {
                return ResourceManager.GetString("ProcessingTerrainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save .terrain File.
        /// </summary>
        public static string SaveTerrainFile {
            get {
                return ResourceManager.GetString("SaveTerrainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Height Map.
        /// </summary>
        public static string SelectHeightMap {
            get {
                return ResourceManager.GetString("SelectHeightMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SplatMap.
        /// </summary>
        public static string SelectSplatMap {
            get {
                return ResourceManager.GetString("SelectSplatMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SplatMap:.
        /// </summary>
        public static string SplatMap {
            get {
                return ResourceManager.GetString("SplatMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional - Select SplatMap file.
        /// </summary>
        public static string SplatMapWatermark {
            get {
                return ResourceManager.GetString("SplatMapWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Processing.
        /// </summary>
        public static string StartProcessing {
            get {
                return ResourceManager.GetString("StartProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Size (2^n + 1).
        /// </summary>
        public static string TileSize {
            get {
                return ResourceManager.GetString("TileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain data processing complete!.
        /// </summary>
        public static string TerrainProcessingComplete {
            get {
                return ResourceManager.GetString("TerrainProcessingComplete", resourceCulture);
            }
        }
    }
}
