// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Terrain
{
    public static partial class RiverStrideLightingKeys
    {
        public static readonly ObjectParameterKey<Texture> EnvironmentMapTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> SceneShadowMapTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> EnvironmentMapSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<SamplerState> SceneShadowSampler = ParameterKeys.NewObject<SamplerState>();
        public static readonly ValueParameterKey<Vector3> _SceneSunDirection = ParameterKeys.NewValue<Vector3>(new Vector3(0.0f,-1.0f,0.0f));
        public static readonly ValueParameterKey<Vector3> _SceneSunColor = ParameterKeys.NewValue<Vector3>(new Vector3(0.0f,0.0f,0.0f));
        public static readonly ValueParameterKey<Matrix> _EnvironmentSkyMatrix = ParameterKeys.NewValue<Matrix>(new Vector4x4(1.0f,0.0f,0.0f,0.0f,0.0f,1.0f,0.0f,0.0f,0.0f,0.0f,1.0f,0.0f,0.0f,0.0f,0.0f,1.0f));
        public static readonly ValueParameterKey<float> _EnvironmentIntensity = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _EnvironmentMipCount = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<int> _SceneShadowCascadeCount = ParameterKeys.NewValue<int>(0);
        public static readonly ValueParameterKey<float> _SceneShadowBlendCascades = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> _SceneShadowFadeFactor = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _SceneShadowDepthBias = ParameterKeys.NewValue<float>(0.01f);
        public static readonly ValueParameterKey<float> _SceneShadowKernelScale = ParameterKeys.NewValue<float>(0.0009765625f);
        public static readonly ValueParameterKey<float> _SceneShadowScreenSpaceScale = ParameterKeys.NewValue<float>(16384.0f);
        public static readonly ValueParameterKey<float> _SceneShadowCascadeSplits = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Matrix> _SceneWorldToShadowCascadeUV = ParameterKeys.NewValue<Matrix>();
    }
}
