// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Terrain
{
    public static partial class RiverBottomKeys
    {
        public static readonly ValueParameterKey<float> _BankFade = ParameterKeys.NewValue<float>(0.025f);
        public static readonly ValueParameterKey<float> _Depth = ParameterKeys.NewValue<float>(0.15f);
        public static readonly ValueParameterKey<float> _DepthWidthPower = ParameterKeys.NewValue<float>(2.0f);
        public static readonly ValueParameterKey<float> _MapExtent = ParameterKeys.NewValue<float>(4096.0f);
        public static readonly ValueParameterKey<float> _WorldToMapUnitScale = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<Vector3> _CameraWorldPosition = ParameterKeys.NewValue<Vector3>(new Vector3(0.0f,0.0f,0.0f));
        public static readonly ValueParameterKey<float> _DepthFakeFactor = ParameterKeys.NewValue<float>(2.0f);
        public static readonly ValueParameterKey<float> _TextureUvScale = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _OceanFadeRate = ParameterKeys.NewValue<float>(0.8f);
        public static readonly ValueParameterKey<float> _BankAmount = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> _WaterHeight = ParameterKeys.NewValue<float>(3.0f);
        public static readonly ValueParameterKey<float> _BottomUvScale = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _ParallaxStrength = ParameterKeys.NewValue<float>(0.04f);
        public static readonly ValueParameterKey<int> _ParallaxIterations = ParameterKeys.NewValue<int>(10);
        public static readonly ValueParameterKey<float> _BottomNormalStrength = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> _BottomEnvironmentIntensity = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<Vector4> BottomProperties = ParameterKeys.NewValue<Vector4>(new Vector4(0.0f,0.35f,0.0f,1.0f));
        public static readonly ValueParameterKey<Vector4> BottomColorShallow = ParameterKeys.NewValue<Vector4>(new Vector4(0.28f,0.22f,0.16f,1.0f));
        public static readonly ValueParameterKey<Vector4> BottomColorDeep = ParameterKeys.NewValue<Vector4>(new Vector4(0.10f,0.075f,0.05f,1.0f));
        public static readonly ObjectParameterKey<Texture> BottomDiffuseTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> BottomNormalTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> BottomPropertiesTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> BottomDepthTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> BottomTextureSampler = ParameterKeys.NewObject<SamplerState>();
    }
}
