// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Terrain
{
    public static partial class MaterialTerrainDisplacementKeys
    {
        public static readonly ObjectParameterKey<Texture> HeightTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Buffer> InstanceBuffer = ParameterKeys.NewObject<Buffer>();
        public static readonly ValueParameterKey<Vector2> HeightTextureTexelSize = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> HeightmapDimensionsInSamples = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<float> HeightScale = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<int> BaseChunkSize = ParameterKeys.NewValue<int>();
    }
}
